Generating pipelines...
2 pipelines have been generated.

Pipeline1: Doing geneset analysis on the samples.
[ 2:03PM] 1.convert_signal_to_tdf
[ 2:03PM] 2.log_signal
[ 2:04PM] 3.fill_missing_with_zeros
[ 2:04PM] 4.normalize_samples_with_quantile
[ 2:06PM] 5.convert_signal_to_pcl
[ 2:06PM] 6.center_genes
[ 2:06PM] 7.convert_signal_to_pcl
[ 2:06PM] 8.normalize_genes
[ 2:06PM] 9.annotate_probes
[ 2:10PM] 10.remove_duplicate_genes
[ 2:14PM] 11.score_pathway_with_geneset
Traceback (most recent call last):
  File "/home/xchen/chencode/Betsy/scripts/run_protocol.py", line 203, in <module>
    main()
  File "/home/xchen/chencode/Betsy/scripts/run_protocol.py", line 192, in main
    parameters,clean_up=args.clean_up)
  File "/home/xchen/chencode/Betsy/scripts/run_protocol.py", line 69, in run_protocol
    out_files = rule_engine.run_pipeline(pipeline, objects,clean_up=clean_up)
  File "/home/xchen/chencode/Betsy/Betsy/rule_engine.py", line 224, in run_pipeline
    analysis,objects,pipeline_sequence,clean_up=clean_up)
  File "/home/xchen/chencode/Betsy/Betsy/rule_engine.py", line 169, in run_module
    analysis.parameters, objects, pipeline_sequence)
  File "/home/xchen/chencode/Betsy/Betsy/modules/score_pathway_with_geneset.py", line 20, in run
    allgenes = parameters['allgenes']
KeyError: 'allgenes'
