Generating pipelines...
9 pipelines have been generated.

Pipeline1: Preprocessing the signal file.
[ 2:25PM] 1.extract_illumina_idat_files
/tmp/tmp2_H8Rk/no_table.myfile0_path.b1351847decf3bb9.363939313031303031382e7a6970
There is no illumina idat file in the input.
[ 2:25PM] 2.preprocess_illumina
Traceback (most recent call last):
  File "/home/xchen/chencode/Betsy/scripts/run_protocol.py", line 203, in <module>
    main()
  File "/home/xchen/chencode/Betsy/scripts/run_protocol.py", line 192, in main
    parameters,clean_up=args.clean_up)
  File "/home/xchen/chencode/Betsy/scripts/run_protocol.py", line 69, in run_protocol
    out_files = rule_engine.run_pipeline(pipeline, objects,clean_up=clean_up)
  File "/home/xchen/chencode/Betsy/Betsy/rule_engine.py", line 224, in run_pipeline
    analysis,objects,pipeline_sequence,clean_up=clean_up)
  File "/home/xchen/chencode/Betsy/Betsy/rule_engine.py", line 156, in run_module
    module, module_name, pipeline_sequence, analysis, objects))
  File "/home/xchen/chencode/Betsy/Betsy/rule_engine.py", line 112, in make_module_wd_name
    single_object = module.get_identifier(analysis.parameters, objects)
  File "/home/xchen/chencode/Betsy/Betsy/modules/preprocess_illumina.py", line 154, in get_identifier
    %single_object.identifier)
AssertionError: the input file /home/xchen/chencode/examples/sample_analysis/extract_illumina_idat_files_BETSYHASH1_d995e79827110d7aeb60401ab6bf6db8/idat_files_path.b1351847decf3bb9.363939313031303031382e7a6970 for illumina does not exist
