Generating pipelines...
6 pipelines have been generated.

Pipeline1: Preprocessing the signal file.
[ 1:49PM] 1.extract_CEL_files
/home/xchen/chencode/upload/no_table.myfile0_path.973a8bd5b817c804.475345383238365f666f6c6465722e7a6970.zip
GSE8286_folder/
GSE8286_folder/GSM205594.CEL.gz
GSE8286_folder/GSM205558.CEL.gz
GSE8286_folder/GSM205556.CEL.gz
GSE8286_folder/GSM205592.CEL.gz
GSE8286_folder/GSM205587.CEL.gz
GSE8286_folder/GSM205588.CEL.gz
GSE8286_folder/GSM205590.CEL.gz
GSE8286_folder/GSM205591.CEL.gz
GSE8286_folder/GSM205585.CEL.gz
Traceback (most recent call last):
  File "/home/xchen/chencode/Betsy/scripts/run_protocol.py", line 203, in <module>
    main()
  File "/home/xchen/chencode/Betsy/scripts/run_protocol.py", line 192, in main
    parameters,clean_up=args.clean_up)
  File "/home/xchen/chencode/Betsy/scripts/run_protocol.py", line 69, in run_protocol
    out_files = rule_engine.run_pipeline(pipeline, objects,clean_up=clean_up)
  File "/home/xchen/chencode/Betsy/Betsy/rule_engine.py", line 224, in run_pipeline
    analysis,objects,pipeline_sequence,clean_up=clean_up)
  File "/home/xchen/chencode/Betsy/Betsy/rule_engine.py", line 169, in run_module
    analysis.parameters, objects, pipeline_sequence)
  File "/home/xchen/chencode/Betsy/Betsy/modules/extract_CEL_files.py", line 13, in run
    filenames = os.listdir(directory)
OSError: [Errno 2] No such file or directory: '/tmp/tmpoX93Y9/no_table.myfile0_path.973a8bd5b817c804.475345383238365f666f6c6465722e7a6970'
